version: "3.8"

services:
  web:
    build: .
    restart: always
    ports:
      - 8087:80
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "100M"
          pids: 100
